### PR TITLE
Leaky mempool missing-requests fixed.

### LINKED ISSUE #2324: Mempool missing requests increase over time.

### PR DESCRIPTION
**Pull request by kape1395**
Closes https://github.com/iotaledger/wasp/issues/2324.

### CODE REVIEW

File: packages/chain/mempool/distSync/distSync.go [hunk 1]
```diff
@@ -203,13 +216,20 @@ func (dsi *distSyncImpl) handleInputTimeTick() gpa.OutMessages {
 	msgs := gpa.NoMessages()
 	nodePerm := dsi.rnd.Perm(nodeCount)
 	counter := 0
-	dsi.needed.ForEach(func(_ isc.RequestRefKey, reqRef *isc.RequestRef) bool { // Access is randomized.
+	dsi.needed.ForEach(func(reqRefKey isc.RequestRefKey, reqNeeded *distSyncReqNeeded) bool { // Access is randomized.
+		stillNeeded := lo.ContainsBy(reqNeeded.waiters, func(ctx context.Context) bool { return ctx.Err() == nil })
+		if !stillNeeded {
+			dsi.needed.Delete(reqRefKey)
```
Comment (dessaya) [inline packages/chain/mempool/distSync/distSync.go:222]: Does deleting inside ForEach not break the loop?

**Review by dessaya — APPROVED** [review]

File: packages/chain/mempool/distSync/distSync.go (hunk 1 above)
Comment (kape1395) [reply packages/chain/mempool/distSync/distSync.go:222]: It uses a map inside, and it is safe to delete map entries while iterating over it, afaik.
E.g. https://stackoverflow.com/questions/23229975/is-it-safe-to-remove-selected-keys-from-map-within-a-range-loop

**Review by Juliusan — COMMENTED** [review]
Looks good to me
