### PR TITLE
fix: Add network check in wasp-cli

### LINKED ISSUE #1994: wasp-cli should check the hrp of the config and the target network.

### PR DESCRIPTION
**Pull request by howjmay**
Closes #1994

### CODE REVIEW

File: tools/wasp-cli/cli/config/config.go [hunk 1]
```diff
@@ -118,7 +118,11 @@ func AddChain(name, chainID string) {
 }
 
 func GetChain(name string) isc.ChainID {
-	chainID, err := isc.ChainIDFromString(viper.GetString("chains." + name))
+	configChainID := viper.GetString("chains." + name)
+	chainID, err := isc.ChainIDFromString(configChainID)
```
Comment (muXxer) [inline tools/wasp-cli/cli/config/config.go]: IMO we should do that check in a bit cleaner way, to understand whats going on.

I would use the networkPrefix parameter from the `networkPrefix, addr, err := iotago.ParseBech32(bech32)` , which is the HRP, and compare it with the `parameters.L1().Protocol.Bech32HRP`.

**Review by muXxer — CHANGES_REQUESTED** [review]

File: tools/wasp-cli/cli/config/config.go (hunk 1 above)
Comment (howjmay) [reply tools/wasp-cli/cli/config/config.go]: Fixed. However, I am not sure if the current error message is a good one

File: tools/wasp-cli/cli/config/config.go [hunk 2]
```diff
@@ -118,7 +119,16 @@ func AddChain(name, chainID string) {
 }
 
 func GetChain(name string) isc.ChainID {
-	chainID, err := isc.ChainIDFromString(viper.GetString("chains." + name))
+	configChainID := viper.GetString("chains." + name)
+	networkPrefix, _, err := iotago.ParseBech32(configChainID)
+	log.Check(err)
+
+	if networkPrefix != parameters.L1().Protocol.Bech32HRP {
+		err = fmt.Errorf("target network not matches wasp-cli config")
```
Comment (muXxer) [inline tools/wasp-cli/cli/config/config.go]:
```suggestion
		err = fmt.Errorf("target network of the L1 node does not match the wasp-cli config")
```

**Review by muXxer — APPROVED** [review]
