### PR TITLE
Fix `wasp-cli mint` command (fixes #211)

### LINKED ISSUE #211: mint error
I use the wasp-cluster. Balance is 1mi but with mint i get the following error message
`error: prepareColoredBalancesOutput: no tokens to transfer`

### PR DESCRIPTION
**Pull request by dessaya**

### CODE REVIEW

File: tools/cluster/tests/wasp-cli_test.go [hunk 1]
```diff
@@ -199,3 +200,38 @@ func TestWaspCLIBlobRegistry(t *testing.T) {
...
+	{
+		found := false
+		for _, line := range out {
+			if strings.Contains(line, color) {
+				require.Regexp(t, fmt.Sprintf("(?m)%s:[[:space:]]+1000$", color), line)
+				found = true
+			}
+		}
+		require.True(t, found)
+	}
```
Comment (jorgemmsilva) [inline tools/cluster/tests/wasp-cli_test.go]: testing by checking console output seems like a slippery slope. couldn't we just check if the tokens were minted instead?

**Review by jorgemmsilva — APPROVED** [review]

**Review by lunfardo314 — APPROVED** [review]

File: tools/cluster/tests/wasp-cli_test.go (hunk 1 above)
Comment (dessaya) [reply tools/cluster/tests/wasp-cli_test.go]: The purpose of the test is to verify the behavior of `wasp-cli`, and the output is part of what is being tested here. We want to assert that the command shows a helpful message when it succeeds.

Comment (dessaya) [reply tools/cluster/tests/wasp-cli_test.go]: Although it's debatable that this test is testing two things: the `mint` and `balance` commands, and maybe it should be split in two. I'll do that.
